
services:
  # Backend (ExpressJS API)
  backend:
    build:
      context: .
    container_name: mes-system
    environment:
      - NODE_ENV=production
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=aditya
      - PGDATABASE=mes_db
      - PGPORT=5432
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mes-network

  # Frontend (Vue.js)
  frontend:
    build:
      context: ./frontend
    container_name: mes-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - mes-network

  # PostgreSQL Database
  db:
    image: postgres:16
    container_name: mes-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aditya
      - POSTGRES_DB=mes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mes-network

networks:
  mes-network:
    driver: bridge

volumes:
  postgres-data:
